[build]
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/flutter_bootstrap.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
    Content-Type = "application/javascript"