"""add currency conversion fields to transactions

Revision ID: 6a0d9c671800
Revises: af8aaaa687cb
Create Date: 2026-03-31 18:37:36.409255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0d9c671800'
down_revision: Union[str, Sequence[str], None] = 'af8aaaa687cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount_original', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('original_currency', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=False))
    op.add_column('transactions', sa.Column('amount_converted', sa.Numeric(precision=12, scale=2), nullable=False))
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'amount_converted')
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'original_currency')
    op.drop_column('transactions', 'amount_original')
    # ### end Alembic commands ###
