"""add base_currency to users

Revision ID: b8110f14abb0
Revises: 795f960e6e57
Create Date: 2026-03-31 19:51:01.737009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8110f14abb0'
down_revision: Union[str, Sequence[str], None] = '795f960e6e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. cria coluna permitindo null
    op.add_column('users', sa.Column('base_currency', sa.String(), nullable=True))

    # 2. preenche dados existentes
    op.execute("UPDATE users SET base_currency = 'BRL'")

    # 3. torna obrigatório
    op.alter_column('users', 'base_currency', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'base_currency')
    # ### end Alembic commands ###
