"""create monthly closures table

Revision ID: e570d9f6bdf2
Revises: 6a0d9c671800
Create Date: 2026-03-31 18:54:21.195916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e570d9f6bdf2'
down_revision: Union[str, Sequence[str], None] = '6a0d9c671800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('investment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transactions_count', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_closures_id'), 'monthly_closures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_closures_id'), table_name='monthly_closures')
    op.drop_table('monthly_closures')
    # ### end Alembic commands ###
